-------------------------------------------------------------------------------
Test set: com.restapi.mobileappws.implementations.UserServiceImplTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.606 s <<< FAILURE! - in com.restapi.mobileappws.implementations.UserServiceImplTest
testCreateUser_IllegalStateException  Time elapsed: 0.041 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalStateException> but was: <com.restapi.mobileappws.exceptions.UserServiceException>
	at com.restapi.mobileappws.implementations.UserServiceImplTest.testCreateUser_IllegalStateException(UserServiceImplTest.java:168)
Caused by: com.restapi.mobileappws.exceptions.UserServiceException: Record already exist
	at com.restapi.mobileappws.implementations.UserServiceImplTest.lambda$testCreateUser_IllegalStateException$1(UserServiceImplTest.java:169)
	at com.restapi.mobileappws.implementations.UserServiceImplTest.testCreateUser_IllegalStateException(UserServiceImplTest.java:168)

